apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  pipeline:
    stages:
      - name: K8S_CANARY_ROLLOUT
      - name: WAIT_APPROVAL
        with:
          approvers:
            - hello-pipecd
      - name: K8S_PRIMARY_ROLLOUT
